Fetch proposal details and Vote Status
planetdecred/dcrlibwallet pull request #161
Opened 2020-07-30 11:47 UTC by codemaestro64

This adds functions that fetch proposal details and vote status for both individual proposals and all proposals

Fixes #158 and #159

2020-08-25 00:41 UTC, C-ollins requested changes

2020-08-25 00:41 UTC, C-ollins commented on politeia_sync.go
> +)
This should be declared in `politeia.go` but here's how to make these constants available for mobile.
```suggestion
const (
      // ProposalCategory
	ProposalCategoryAllProposals       int32 = 1
	ProposalCategoryPreProposals             = 2
	ProposalCategoryActiveProposals          = 3
	ProposalCategoryApprovedProposals        = 4
	ProposalCategoryRejectedProposals        = 5
	ProposalCategoryAbandonedProposals       = 5
)
```
Make sure it is `int32`, using int is unnecessary in this case.

2020-08-25 00:41 UTC, C-ollins commented on politeia.go
> +func processResult(result interface{}, err error) (string, error) {
Make this function part of `Politeia` struct since it is specifically for proposal. it can also be renamed to `MarshalResult`.

2020-08-25 00:41 UTC, C-ollins commented on politeia_sync.go
> +func diff(tokenInventory, savedTokens []string) []string {
Make this function part of the `Politeia` struct and give it a name that better defines what it does. I initially thought it was a math function.

2020-08-25 00:41 UTC, C-ollins commented on politeia_sync.go
> +	log.Infof("Politeia sync: found new proposal %s", proposal.CensorshipRecord.Token)
Remove these logs.

2020-08-25 00:41 UTC, C-ollins commented on types.go
> +type Err struct {
This struct doesn't seem to have a use outside `politeia_client.go`, it can be declared there instead.

2020-08-25 00:41 UTC, C-ollins commented on types.go
> +	//Type             VoteT              `json:"type,omitempty"`
Delete comment.

2020-08-25 00:41 UTC, C-ollins commented on types.go
> +/** begin politeia types */
There's a lot of `int` usage in this file that doesn't seem necessary. Ints get converted to Long on gomobile and it's not really convenient to use so please use `int32` where possible.

2020-09-02 15:33 UTC, C-ollins requested changes

2020-09-06 19:09 UTC, C-ollins requested changes

2020-09-06 19:09 UTC, C-ollins commented on types.go
> +}
I don't think these `ProposalVote-` types are unnecessary, It should be reduced to the basic data needed by the frontend ie
```
type ProposalVoteOption struct {
	YesCount int32
	NoCount  int32
}
```

2020-09-23 11:56 UTC, C-ollins approved these changes

2020-09-23 11:56 UTC, C-ollins commented on types.go
> +type proposalServerVersion struct {
Move the unexported structs to any politeia file.

2020-09-23 11:56 UTC, C-ollins commented on politeia_notifications.go
> +func (p *Politeia) AddNotificationListener(notificationListener ProposalNotificationListener, uniqueIdentifier string) error {
All the contents in this file should go it politeia_sync.go, politeia files are getting too much.

2020-09-23 11:58 UTC, C-ollins requested changes

2020-09-23 11:58 UTC, C-ollins commented on politeia_notifications.go
> +func (p *Politeia) AddNotificationListener(notificationListener ProposalNotificationListener, uniqueIdentifier string) error {
All the contents in this file should go it politeia_sync.go, politeia files are getting too much.

2020-09-23 11:58 UTC, C-ollins commented on types.go
> +type proposalServerVersion struct {
Move unexported structs to any politeia file.

2020-11-02 14:25 UTC, C-ollins requested changes
I got this when syncing proposals from dcrandroid
```
I/GoLog: 2020-11-02 13:33:40.754 [INF] DLWL: Politeia sync: fetching token inventory
2020-11-02 14:33:42.747 com.decred.dcrandroid.testnet I/GoLog: 2020-11-02 13:33:42.745 [INF] DLWL: Politeia sync: fetching 100 new proposals
2020-11-02 14:33:50.613 com.decred.dcrandroid.testnet E/Go: panic: runtime error: slice bounds out of range [20:14]
2020-11-02 14:33:50.613 com.decred.dcrandroid.testnet E/Go: goroutine 18 [running, locked to thread]:
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: github.com/planetdecred/dcrlibwallet.(*Politeia).syncBatchProposals(0x98858780, 0x5, 0x6a08c4a0, 0xe, 0x2c, 0x1, 0x0)
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: 	/Users/collins/go/src/github.com/planetdecred/dcrlibwallet/politeia_sync.go:162 +0x48a
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: github.com/planetdecred/dcrlibwallet.(*Politeia).fetchAllUnfetchedProposals(0x98858780, 0x775f8b00, 0x0, 0x0, 0x0, 0x0, 0x0)
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: 	/Users/collins/go/src/github.com/planetdecred/dcrlibwallet/politeia_sync.go:136 +0x560
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: github.com/planetdecred/dcrlibwallet.(*Politeia).Sync(0x98858780, 0xc9d58680, 0x98858780)
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: 	/Users/collins/go/src/github.com/planetdecred/dcrlibwallet/politeia_sync.go:88 +0x308
2020-11-02 14:33:50.615 com.decred.dcrandroid.testnet E/Go: main.proxydcrlibwallet_Politeia_Sync(0xfffffc85, 0xc96cc645)
2020-11-02 14:33:50.616 com.decred.dcrandroid.testnet E/Go: 	/var/folders/_z/21zf85t530b1wz5mzpmrqrkc0000gp/T/gomobile-work-245391752/src/gobind/go_dcrlibwalletmain.go:1992 +0x51
2020-11-02 14:33:50.617 com.decred.dcrandroid.testnet E/Go: main._cgoexpwrap_1c898d3f9d99_proxydcrlibwallet_Politeia_Sync(0xfffffc85, 0x267a)
2020-11-02 14:33:50.617 com.decred.dcrandroid.testnet E/Go: 	_cgo_gotypes.go:3163 +0x22
```

2020-11-02 14:25 UTC, C-ollins commented on politeia_sync.go
> +}
What this sync does is fetch data from an API, a progress listener is not needed for this and it's not also implemented by the frontend.

2020-11-02 14:25 UTC, C-ollins commented on politeia_sync.go
> +func (p *Politeia) getUniqueSliceElements(tokenInventory, savedTokens []string) []string {
```suggestion
func (p *Politeia) getUniqueTokens(tokenInventory, savedTokens []string) []string {
```

2020-11-02 14:25 UTC, C-ollins commented on politeia_sync.go
> +func (p *Politeia) syncProgressListeners() []ProposalSyncProgressListener {
What is this function needed for?

2020-11-02 14:25 UTC, C-ollins commented on types.go
>  }
Proposals do not need a progress listener

2020-11-22 05:33 UTC, song50119 commented
I got this when trying to build & run on Godcr
```
# github.com/planetdecred/godcr/wallet
wallet/commands.go:568:52: undefined: dcrlibwallet.ProposalSyncProgressListener
wallet/commands.go:569:20: wal.multi.Politeia.AddSyncPropogressListener undefined (type *dcrlibwallet.Politeia has no field or method AddSyncPropogressListener)
```

2021-01-04 14:11 UTC, C-ollins commented
Moved to #170.

2021-01-04 14:11 UTC, closed without merging